config/routes.rb
Rails.application.routes.draw do
  
  resources :users
  resources :sessions, :only => [ :new, :create, :destroy ]

  get '/contact', :to => 'pages#contact'
  get '/about', :to => 'pages#about'
  get '/help', :to => 'pages#help'
  get '/signup', :to => 'users#new'
  get '/signin', :to => 'sessions#new'
  get '/signout', :to => 'sessions#destroy'

  root :to => 'pages#home'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class User < ActiveRecord::Base
	attr_accessor :password

	email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	
	validates :name, :presence => true, :length => { :maximum => 50 }
	validates :email, :presence => true, :format => { :with => email_regex }, :uniqueness => { :case_sensitive => false }
	validates :password, :presence => true, :confirmation => true, :length => { :minimum => 6, :maximum => 40 }

	before_save :encrypt_password

	def has_password?(submitted_password)
		encrypted_password == encrypt(submitted_password)
	end

	def self.authenticate(email, submitted_password)
		user = find_by_email(email)
		return nil if user.nil?
		return user if user.has_password?(submitted_password)
	end

	def self.authenticate_with_salt(id, cookie_salt)
		user = find_by_id(id)
		(user && user.salt == cookie_salt) ? user : nil
	end

	private

	def encrypt_password 
		self.salt = make_salt if new_record?
		self.encrypted_password = encrypt(password)
	end

	def encrypt(string)
		secure_hash("#{salt}--#{string}")
	end

	def make_salt
		secure_hash("#{Time.now.utc}--#{password}")
	end

	def secure_hash(string)
		Digest::SHA2.hexdigest(string)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  	@title = 'Home'
  end

  def contact
  	@title = 'Contact'
  end

  def about
  	@title = 'About'
  end

  def help
  	@title = 'Help'
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  	@title = "Sign In"
  end

  def create
  	user = User.authenticate(params[:session][:email], params[:session][:password])

  	if user.nil?
  		flash.now[:error] = "Invalid email/password combination."
  		@title = "Sign In"
  		render 'new'
  	else
  		sign_in user
  		redirect_to user
  	end
  end

  def destroy
  	sign_out
  	redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	@user = User.find(params[:id])
    @title = @user.name
  end

  def new
  	@user = User.new
    @title = "Sign Up"
  end

  def create
  	@user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      @title = "Sign Up"
      render 'new'
    end
  end

  private

  def user_params
  	params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def title
		base_title = "Ruby on Rails Tutorial Sample App"
		if @title.nil?
			base_title
		else
			"#{base_title} | #{@title}"
		end
	end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in(user)
		cookies.permanent.signed[:remember_token] = [user.id, user.salt]
		self.current_user = user
	end

	def current_user=(user)
		@current_user = user
	end

	def current_user
		@current_user ||= user_from_remember_token
	end

	def signed_in?
		!current_user.nil?
	end

	def sign_out
		cookies.delete(:remember_token)
		self.current_user = nil
	end

	private 

		def user_from_remember_token
			User.authenticate_with_salt(*remember_token)
		end

		def remember_token
			cookies.signed[:remember_token] || [nil, nil]
		end
end

app/helpers/users_helper.rb
module UsersHelper

	def gravatar_for(user, options = { :size => 50 })
		gravatar_image_tag(
			user.email.downcase,
			:alt => user.name,
			:class => 'gravatar',
			:gravatar => options
		)
	end

end

app/views/layouts/_footer.html.erb
	<footer class="container">
		<ul>
			<li><%= link_to "About", about_path %></li>
			<li><%= link_to "Contact", contact_path %></li>
			<li><a href="http://news.railstutorial.org/" target="_blank">News</a></li>
			<li><a href="http://www.railstutorial.org/" target="_blank">Rails Tutorial</a></li>
		</ul>
	</footer>

app/views/layouts/_nav.html.erb
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
		<div class="container">
			<div class="navbar-header">
    			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-nav">
    				<span class="icon-bar"></span>
    				<span class="icon-bar"></span>
    				<span class="icon-bar"></span>
    			</button>
    			<%= link_to "Sample App", root_path, class: 'navbar-brand' %>
    		</div>
    		<div class="collapse navbar-collapse" id="main-nav">
    			<ul class="nav navbar-nav pull-right">
    				<li><%= link_to "Home", root_path %></li>
    				<li><%= link_to "Help", help_path %></li>
    				<li><%= link_to "Sign In", '#' %></li>
    			</ul>
    		</div>
  		</div>
	</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title><%= title %></title>
	<%= csrf_meta_tag %>
	<%= stylesheet_link_tag "application", media: "all" %>
</head>
<body>
	<%= render 'layouts/nav' %>

	<div class="wrapper">
		<% flash.each do |key, value| %>
			<div class="container">
				<%= content_tag( :div, value, :class => "flash #{key}" ) %>
			</div>
		<% end %>
		
		<%= yield %>
	</div>

	<%= render 'layouts/footer' %>
	<%= debug(params) if Rails.env.development? %> <!-- Only debug if in development -->
	<%= javascript_include_tag "application" %>
</body>
</html>

app/views/pages/about.html.erb
<div class="container">
	<h1>About</h1>
	<p>This is the about page for the <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a> sample app.</p>
</div>

app/views/pages/contact.html.erb
<div class="container">
	<h1>Contact</h1>
	<p>This is the contact page for the <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a> sample app.</p>
</div>

app/views/pages/help.html.erb
<div class="container">
	<h1>Help</h1>
	<p>Get help on Ruby on Rails Tutorial at the <a href="http://railstutorial.org/help">Rails Tutorial help page</a>. To get help on this sample app. see the <a href="http://railstutorial.org/book">Rails Tutorial book</a>.</p>
</div>

app/views/pages/home.html.erb
<div class="container">
	<h1>Sample App</h1>
	<p>This is the home page for the <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a> sample app.</p>
	<%= link_to 'Sign up now!', signup_path, class: "btn btn-info" %>
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
	<div class="errors">
		<h2><%= pluralize(@user.errors.count, "errors") %> prohibited this user form being saved:</h2>
		<p>There were problems with the following fields:</p>
		<ul>
			<% @user.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/users/new.html.erb
<div class="container">
	<div class="col-md-12">
		<h1>Sign Up</h1>
	</div>
	<div class="col-md-6 col-md-offset-3">
		<%= form_for (@user) do |f| %>
			<%= render 'shared/error_messages' %>
			<div class="form-group">
				<%= f.label :name %>
				<%= f.text_field :name, :class => 'form-control' %>
			</dvi>
			<div class="form-group">
				<%= f.label :email %>
				<%= f.text_field :email, :class => 'form-control' %>
			</dvi>
			<div class="form-group">
				<%= f.label :password %>
				<%= f.password_field :password, :class => 'form-control' %>
			</dvi>
			<div class="form-group">
				<%= f.label :password_confirmation, "Confirmation" %>
				<%= f.password_field :password_confirmation, :class => 'form-control' %>
			</dvi>
			<%= f.submit "Sign Up", :class => 'btn btn-info' %>
		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<div class="container">
	<div class="col-md-2">
		<%= gravatar_for @user, :size => 140 %>
	</div>
	<div class="col-md-7">
		<h1><%= @user.name %></h1>
	</div>
	<div class="col-md-3 sidebar">
		<span><strong>Name</strong> <%= @user.name %></span><br/>
		<span><strong>URL</strong> <%= link_to user_path(@user), @user %></span>
	</div>
</di>